### ISSUE TITLE
Linux版本hoshino出现大量报错

### ISSUE THREAD

**Issue by chenchenriver** [half-ghost/steam_crawler_botV2#1]
![image](https://user-images.githubusercontent.com/93070768/158373545-748249c5-2b5d-4fde-83dd-fb1072961dd0.png)
请问是不支持linux版本吗？
已经完整删除后又重新Git clone，故障依旧

**Comment by half-ghost** [comment]
抱歉，写readme时没全面考虑，linux时因为缺少了字体才会出现这个错误，可以去windows自带的字体库中复制，可以看看我新更新的readme

**Comment by chenchenriver** [comment]
![image](https://user-images.githubusercontent.com/93070768/158376291-d749190b-f4e5-4680-bc23-1d1843ff2e6a.png)
已放入字体，但是依旧报错
![image](https://user-images.githubusercontent.com/93070768/158376375-405afc17-bf18-4a0e-a999-851f69ca03cd.png)

**Comment by half-ghost** [comment]
> ![image](https://user-images.githubusercontent.com/93070768/158376291-d749190b-f4e5-4680-bc23-1d1843ff2e6a.png) 已放入字体，但是依旧报错 ![image](https://user-images.githubusercontent.com/93070768/158376375-405afc17-bf18-4a0e-a999-851f69ca03cd.png)

emmm，你要把字体文件的文件名全部小写，包括后缀

**Comment by chenchenriver** [comment]
谢谢，正常了！
