### ISSUE TITLE
st搜索游戏时报错ERROR: Error:can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by Fatfish588** [half-ghost/steam_crawler_botV2#11]
![image](https://user-images.githubusercontent.com/59791439/221800127-8edca33e-1b14-4aec-886c-83b13c8e2469.png)

自己尝试debug了一下，在steam_crawler()方法里的高低分辨率图片的位置出现这个bug，怪的是列表里前几个结果没问题
搜过几个游戏都是这样，debug复现的是“st搜游戏 Atomic Heart”，在第五个row的时候会报错。环境是MacOS。python3.9.13

**Comment by half-ghost** [comment]
好的，这几天我看看修一下

**Comment by half-ghost** [comment]
已修复
