### ISSUE TITLE
无法获取价格信息

### ISSUE THREAD

**Issue by Cathgao** [half-ghost/steam_crawler_botV2#13]
包括每日推送和今日特惠里的价格全部无法获取
![QQ图片](https://github.com/half-ghost/steam_crawler_botV2/assets/21031564/a1084fc9-9ea6-4789-9171-2ebe76408162)

**Comment by half-ghost** [comment]
最近身体受伤了在养伤，这几天再看看

**Comment by half-ghost** [comment]
顺便问一下，在出现这个情况之后的这几天里，还有这种情况发生吗

**Comment by Cathgao** [comment]
> 便问一下，在出现这个情况之后的这几天里，还有这种情况发生吗

每天都是这样的。主要是我NAS系统盘挂掉了，之前用是正常没问题的，重装之后重新clone就是一直都获取不了价格信息了

**Comment by Cathgao** [comment]
我看hoshino的窗口也没出现什么报错信息，能怎么样获取一点有用的信息吗

**Comment by half-ghost** [comment]
> 我看hoshino的窗口也没出现什么报错信息，能怎么样获取一点有用的信息吗

没有报错信息应该是因为try except掉了，我得看看我怎么写的

**Comment by half-ghost** [comment]
> 我看hoshino的窗口也没出现什么报错信息，能怎么样获取一点有用的信息吗

在 steam_crawler_botV2.py 这个文件里，在第40行里面吧price打印一下，看看出来的是什么结果，如果没打印，那就说明获取不到这个price，进入except里了

**Comment by Cathgao** [comment]
> > 我看hoshino的窗口也没出现什么报错信息，能怎么样获取一点有用的信息吗
> 
> 在 steam_crawler_botV2.py 这个文件里，在第40行里面吧price打印一下，看看出来的是什么结果，如果没打印，那就说明获取不到这个price，进入except里了

打断点调试了，确实没有price，直接进except
![image](https://github.com/half-ghost/steam_crawler_botV2/assets/21031564/f71e4786-41f1-4c43-bab4-8983006d8e0e)

或许是xml的结构改变了吗
![image](https://github.com/half-ghost/steam_crawler_botV2/assets/21031564/223b8c62-0d1c-46cb-aaa0-143a6d698908)

**Comment by Cathgao** [comment]
`row.find(name="div", class_="discount_block search_discount_block")`
36行改成这样可以获取到价格，只是显示比较乱

**Comment by half-ghost** [comment]
> `row.find(name="div", class_="discount_block search_discount_block")` 36行改成这样可以获取到价格，只是显示比较乱

好的，我今晚看看

**Comment by half-ghost** [comment]
> `row.find(name="div", class_="discount_block search_discount_block")` 36行改成这样可以获取到价格，只是显示比较乱

看了下是steam更新搜索页面了，现在那个网址返回的内容是新的，所以之前的匹配规则匹配不到，这几天我得空修修，数据源先暂且切换成小黑盒吧

**Comment by half-ghost** [comment]
已更新，更新文件为 steam_crawler_botV2.py 以及 config.py 这两个

**Comment by half-ghost** [comment]
哦对了更新前记得备份一下config.py，因为config在这次修复中更新了，你之前的配置应该会被覆盖
