### ISSUE TITLE
帮助指令在linux下报错

### ISSUE THREAD

**Issue by baka-onichan** [half-ghost/steam_crawler_botV2#2]
![微信截图_20220320164310](https://user-images.githubusercontent.com/101969230/159155347-338b67ef-776c-44ad-8698-52ba568351ad.png)

**Comment by baka-onichan** [comment]
还有另外一个问题  如果发送以小黑盒 为开头的文本， BOT就会发送 发生了其他错误

**Comment by half-ghost** [comment]
linux那个我最近有人跟我说我才知道的，还有小黑盒的问题，我近期会修复

**Comment by baka-onichan** [comment]
感谢

**Comment by baka-onichan** [comment]
感谢

**Comment by half-ghost** [comment]
> 感谢

应该是改好了，可以更新一下试试

**Comment by baka-onichan** [comment]
已解决
