### ISSUE TITLE
steam_monitor() 未能正确处理特殊情况

### ISSUE THREAD

**Issue by JANERUBBISHTOEAT** [half-ghost/steam_crawler_botV2#3]
问题：
keylol.com 没有标明下一次促销开始时间时，命令“查询促销”导致报错。
![image](https://user-images.githubusercontent.com/55824267/159555200-20464bcc-c104-4ba8-a855-fca350cf1e35.png)

![bug](https://user-images.githubusercontent.com/55824267/159554954-acdfa277-60ad-4a19-a6ba-7455429a7a6c.png)

解决办法：
在函数“steam_monitor()” 内可以判断data 是否为空。
为空则表示下一个时间未知，直接返回一个字符串。
也可以根据网站上的具体情况 返回相应的字符串。

另外在“query_sell_info()” 函数中的Exception 下是否应该return？
![image](https://user-images.githubusercontent.com/55824267/159555817-e53c20d9-8fae-45a0-91de-fa4cc6e81da7.png)

**Comment by JANERUBBISHTOEAT** [comment]
我暂时用的处理办法如下，可供参考
![image](https://user-images.githubusercontent.com/55824267/159557515-1a5739fb-7ead-4583-94ad-1664c966e507.png)

效果如下：
![image](https://user-images.githubusercontent.com/55824267/159557690-fc8b1b1b-92a4-4685-b54f-fd0f84f9efbd.png)

**Comment by half-ghost** [comment]
> 问题： keylol.com 没有标明下一次促销开始时间时，命令“查询促销”导致报错。 ![image](https://user-images.githubusercontent.com/55824267/159555200-20464bcc-c104-4ba8-a855-fca350cf1e35.png)
> 
> ![bug](https://user-images.githubusercontent.com/55824267/159554954-acdfa277-60ad-4a19-a6ba-7455429a7a6c.png)
> 
> 解决办法： 在函数“steam_monitor()” 内可以判断data 是否为空。 为空则表示下一个时间未知，直接返回一个字符串。 也可以根据网站上的具体情况 返回相应的字符串。
> 
> 另外在“query_sell_info()” 函数中的Exception 下是否应该return？ ![image](https://user-images.githubusercontent.com/55824267/159555817-e53c20d9-8fae-45a0-91de-fa4cc6e81da7.png)

嗯，这个问题之前我也注意到了，但是当时只出现了一天，所以忘了给他修了，另外这个except确实得加个return，今晚我给他修修然后再更新一下

**Comment by half-ghost** [comment]
可以了，测试了一下应该没啥问题
