### ISSUE TITLE
请问一下proxies的格式

### ISSUE THREAD

**Issue by SanaChitose** [half-ghost/steam_crawler_botV2#4]
可以请大佬给一个example吗？

**Comment by SanaChitose** [comment]
如果对协议有要求，也麻烦一并提出来，感谢

**Comment by half-ghost** [comment]
分为对http和https的代理，格式就是"http":"" "https":"",""内填入的是代理地址，比如我用的是socks5协议的代理，就填入socks5://username:password@ip。取决于你想填入的代理协议。这里边应该对协议没有啥要求，不过你如果要用sock协议的话那就得先装pysocks。因为我自己有个socks5的代理，所以其他的代理格式没弄过，可以百度一下requests里的代理怎么填

**Comment by half-ghost** [comment]
[![q44E5Q.jpg](https://s1.ax1x.com/2022/04/01/q44E5Q.jpg)](https://imgtu.com/i/q44E5Q)

**Comment by SanaChitose** [comment]
> 分为对http和https的代理，格式就是"http":"" "https":"",""内填入的是代理地址，比如我用的是socks5协议的代理，就填入socks5://username:password@ip。取决于你想填入的代理协议。这里边应该对协议没有啥要求，不过你如果要用sock协议的话那就得先装pysocks。因为我自己有个socks5的代理，所以其他的代理格式没弄过，可以百度一下requests里的代理怎么填

感谢大佬指教！
