### ISSUE TITLE
小黑盒特惠命令出错

### ISSUE THREAD

**Issue by Sasa-kid** [half-ghost/steam_crawler_botV2#7]
提示:

哦吼,获取信息出错了,报错内容为'price',请检查运行日志!

发生了其他错误,报错内容为local variable 'data' referenced before assignment,请检查运行日志!

**Comment by half-ghost** [comment]
本来想今晚测试一下，结果刚刚试了没问题，等下次问题出现的时候再具体测试看看怎么修复

**Comment by half-ghost** [comment]
已修复，以前的类似情况现在估计不会再出现了
