### ISSUE TITLE
多个群推送喜加一时有概率被TX冻结

### ISSUE THREAD

**Issue by baka-onichan** [half-ghost/steam_crawler_botV2#8]
不知道是触发了TX的什么机制，已经发现该问题两次了

**Comment by half-ghost** [comment]
> 不知道是触发了TX的什么机制，已经发现该问题两次了

这个我也遇到过，似乎和群有关，比如群星级之类的，插件这边没办法去怎么改，有些群的定时任务全都没问题，有些部分能发部分不行，有些是全都不行，这个挺玄学的，如果定时发送发不出来的话，请尝试用主动发送指令吧

**Comment by half-ghost** [comment]
我修改了一下代码，文字不行转合并，合并不行转图片，只能做到这个样子了，我自己试了一下，发不出去的群还是发不出去，3中方法全给tx防住了，你要的话也可以更新一下试试，如果还是不行的话那就真的没办法了
